name: Test implementations for aoc 2024
on:
  push:
    branches:
      - 2024-rust
      # We could also add `main` here if this is a long-lived branch
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test project
        run: cargo test --verbose
